language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install coveralls
  - pip install -r pip_requirements_readthedocs.txt
  - pip install -r pip_requirements_tests.txt
# command to run tests
script:
  - set -e
  - python --version
  - python -m coverage run --source=pyxcp test/run_all.py
  - python -m coverage xml -i --include */asammdf/*
  - if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then python-codacy-coverage -r coverage.xml; fi
  - python -m sphinx -nW -b html documentation documentation/_build/html

after_success:
    coveralls
