language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r pip_requirements_readthedocs.txt
  - pip install -r pip_requirements_tests.txt
# command to run tests
script:
  - set -e
  - python --version
  - python -m coverage run test/run_all.py
  - python -m coverage xml -i --include */asammdf/*
  - python-codacy-coverage -r coverage.xml
  - python -m sphinx -nW -b html documentation documentation/_build/html

after_success:
